FROM alpine:3.9

# Install packages
RUN \
  wget -O /etc/apk/keys/phpearth.rsa.pub https://repos.php.earth/alpine/phpearth.rsa.pub && \
  echo "https://repos.php.earth/alpine/v3.9" >> /etc/apk/repositories && \
  apk --no-cache add php7.3 php7.3-fpm php7.3-mysqli php7.3-json php7.3-openssl php7.3-curl \
    php7.3-zlib php7.3-xml php7.3-phar php7.3-intl php7.3-dom php7.3-xmlreader php7.3-ctype php7.3-session \
    php7.3-mbstring php7.3-gd php7.3-soap php7.3-redis php7.3-zip php7.3-pdo php7.3-opcache php7.3-iconv \
    php7.3-imap php7.3-xmlwriter php7.3-xmlrpc php7.3-sockets php7.3-fileinfo php7.3-exif php7.3-pdo_mysql \
    php7.3-posix php7.3-shmop php7.3-xsl php7.3-wddx php7.3-bcmath php7.3-simplexml php7.3-tokenizer \
    php7.3-xdebug \
    nginx supervisor curl mc mysql-client redis bash git

# Configure PHP-FPM
COPY php-fpm-pool.conf /etc/php/7.3/php-fpm.conf
COPY php-fpm-pool-xdebug.conf /etc/php/7.3/php-fpm-xdebug.conf
COPY php-local.ini /etc/php/7.3/conf.d/99-local.ini

RUN \
  mv /etc/php/7.3/conf.d/xdebug.ini /etc/php/7.3/conf.d/xdebug.ini.disabled && \
  cp /etc/php/7.3/php.ini-development /etc/php/7.3/php.ini && \
  cp /etc/php/7.3/php.ini-development /etc/php/7.3/php-xdebug.ini && \
  echo "zend_extension=xdebug.so" >>/etc/php/7.3/php-xdebug.ini && \
  mkdir -p /var/cache/php/opcache && \
  mkdir -p /var/www/magento/var/composer_home && \
  ln -s /var/www/magento/var/composer_home /root/.composer && \
  cd /usr/local/bin && \
  wget https://getcomposer.org/installer && \
  php installer && \
  rm installer && \
  mv composer.phar composer && \
  composer -V

# Configure nginx
RUN \
  rm /etc/nginx/conf.d/default.conf && \
  mkdir -p /etc/nginx/ssl && \
  mkdir -p /var/lib/nginx/logs
#&& \
#  chown -R nginx:nginx /var/lib/nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx-fastcgi.conf /etc/nginx/conf.d/00-fastcgi.conf
COPY nginx-m2.conf /etc/nginx/conf.d/10-m2.conf
COPY local.pem /etc/nginx/ssl/

# Configure supervisord
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY my.cnf /root/.my.cnf

# Setup document root
RUN mkdir -p /var/www/magento && \
  rm -rf /var/www/localhost
#  chown nginx:nginx /var/www/magento

# Switch to use a non-root user from here on
#USER nginx

#COPY --from=builder /go/bin/ftpd /ftpd/
#COPY config.ini /ftpd/

# Add application
WORKDIR /var/www/magento

# Expose the port nginx is reachable on
EXPOSE 80 443

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
