FROM alpine:3.7

# Install packages
RUN \
  wget -O /etc/apk/keys/phpearth.rsa.pub https://repos.php.earth/alpine/phpearth.rsa.pub && \
  echo "https://repos.php.earth/alpine/v3.7" >> /etc/apk/repositories && \
  apk --no-cache add php7.1 php7.1-fpm php7.1-mysqli php7.1-json php7.1-openssl php7.1-curl \
    php7.1-zlib php7.1-xml php7.1-phar php7.1-intl php7.1-dom php7.1-xmlreader php7.1-ctype php7.1-session \
    php7.1-mbstring php7.1-gd php7.1-soap php7.1-redis php7.1-zip php7.1-pdo php7.1-opcache php7.1-iconv \
    php7.1-imap php7.1-xmlwriter php7.1-xmlrpc php7.1-mcrypt php7.1-fileinfo php7.1-exif php7.1-pdo_mysql \
    php7.1-posix php7.1-shmop php7.1-xsl php7.1-wddx php7.1-bcmath php7.1-simplexml php7.1-tokenizer \
    php7.1-xdebug \
    nginx supervisor curl mc mysql-client redis bash git

# Configure PHP-FPM
COPY php-fpm-pool.conf /etc/php/7.1/php-fpm.conf
COPY php-fpm-pool-xdebug.conf /etc/php/7.1/php-fpm-xdebug.conf
COPY php-local.ini /etc/php/7.1/conf.d/99-local.ini

RUN \
  mv /etc/php/7.1/conf.d/xdebug.ini /etc/php/7.1/conf.d/xdebug.ini.disabled && \
  cp /etc/php/7.1/php.ini-development /etc/php/7.1/php.ini && \
  cp /etc/php/7.1/php.ini-development /etc/php/7.1/php-xdebug.ini && \
  echo "zend_extension=xdebug.so" >>/etc/php/7.1/php-xdebug.ini && \
  mkdir -p /var/cache/php/opcache && \
  mkdir -p /var/www/magento/var/composer_home && \
  ln -s /var/www/magento/var/composer_home /root/.composer && \
  cd /usr/local/bin && \
  wget https://getcomposer.org/installer && \
  php installer && \
  rm installer && \
  mv composer.phar composer && \
  composer -V

# Configure nginx
RUN \
  rm /etc/nginx/conf.d/default.conf && \
  mkdir -p /etc/nginx/ssl && \
  mkdir -p /var/lib/nginx/logs
#&& \
#  chown -R nginx:nginx /var/lib/nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx-fastcgi.conf /etc/nginx/conf.d/00-fastcgi.conf
COPY nginx-m2.conf /etc/nginx/conf.d/10-m2.conf
COPY local.pem /etc/nginx/ssl/

# Configure supervisord
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY my.cnf /root/.my.cnf

# Setup document root
RUN mkdir -p /var/www/magento && \
  rm -rf /var/www/localhost
#  chown nginx:nginx /var/www/magento

# Switch to use a non-root user from here on
#USER nginx

#COPY --from=builder /go/bin/ftpd /ftpd/
#COPY config.ini /ftpd/

# Add application
WORKDIR /var/www/magento

# Expose the port nginx is reachable on
EXPOSE 80 443

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
